### PR TITLE
add RemoteCertificateValidationCallback for AsyncClient also

### PR DESCRIPTION
**Pull request by rajatjindal**

### CODE REVIEW

**Comment by bacongobbler** [comment]
This file is auto-generated. The next time we re-generate the client, this change will be wiped out.

Can you please make the appropriate change to the mustache templates, then call `make clean && make`?

https://github.com/fermyon/nomad-dotnet/blob/main/templates/ApiClient.mustache

**Comment by rajatjindal** [comment]
probably because I used dotnet 7.0.100 (and earlier was done using dotnet 6.x), the diff is large. should we keep it minimal (and regenerate client using dotnet 6.x)?

also i am double checking why it started to fail now (or was it never working?)

**Comment by bacongobbler** [comment]
Yes, let's keep it minimal and generate the client using .NET 6.

**Comment by bacongobbler** [comment]
Actually, the changes here are incredibly minimal. I'm happy with merging as-is.

**Review by bacongobbler — APPROVED** [review]

**Comment by rajatjindal** [comment]
I also updated Github workflow to use `dotnet 7.0.x`. (as I imagined code generated using `7.0.x` may not compile with `6.x`).

**Comment by rajatjindal** [comment]
@bacongobbler it seems I don't have permissions to merge this PR, could you please help with that.

**Pull request merged**
